### PR TITLE
Invalidate cache when key not found in key set

### LINKED ISSUE #2: Refreshing cache when keyset is missing/failed
Currently the cache is set to automatically refresh every 24 hours. This means that in case a new keyset is missing or the current keyset is no longer valid, it will fail until the next cache refresh.

A possible solution is to:

1. Refresh the cache automatically if a given key id is not found in the key set
2. Allow the user to manually trigger refresh in case he suspects the keyset is no longer valid

In both cases we may want to consider some rate limit on how often a refresh attempt is allowed (maybe a few minutes?) in case there is some other reason for the failures.

### PR DESCRIPTION
**Pull request by AleF83**
Fixes #2

### CODE REVIEW

File: fetch-jwk.go [hunk 1]
```diff
@@ -40,7 +42,12 @@ func FromIssuerClaim() func(*jwt.Token) (interface{}, error) {
 			return nil, err
 		}
 
-		return getKey(keySet, keyID)
+		key, err := getKey(keySet, keyID)
+		if err == errKeyNotFound {
+			delete(issuerCache, issuer)
+			return FromIssuerClaim()(token)
```
Comment (tomeresk) [inline fetch-jwk.go]: We need some way to stop after first retry, since if the issuer also doesn't have this key this will possibly create an infinite recursion

File: fetch-jwk.go [hunk 2]
```diff
@@ -57,7 +64,12 @@ func FromDiscoverURL(discoverURL string) func(*jwt.Token) (interface{}, error) {
 			return nil, err
 		}
 
-		return getKey(keySet, keyID)
+		key, err := getKey(keySet, keyID)
+		if err == errKeyNotFound {
+			delete(discoverURLsCache, discoverURL)
+			return FromDiscoverURL(discoverURL)(token)
```
Comment (tomeresk) [inline fetch-jwk.go]: same as for issues recursion

File: fetch-jwk.go [hunk 3]
```diff
@@ -73,7 +85,13 @@ func FromJWKsURL(jwksURL string) func(*jwt.Token) (interface{}, error) {
 		if err != nil {
 			return nil, err
 		}
-		return getKey(keySet, keyID)
+
+		key, err := getKey(keySet, keyID)
+		if err == errKeyNotFound {
+			delete(jwksCache, jwksURL)
+			return FromJWKsURL(jwksURL)(token)
```
Comment (tomeresk) [inline fetch-jwk.go]: same as previous comments

**Comment by tomeresk** [comment]
Actually it might be possible (not sure because of my limited knowledge of golang) to extract all 3 of them to a single function which might make it worth it.

You get as parameters the relevant cache (`issuerCache`/`discoverURLsCache`/`jwksCache`), the fetching function (`getKeySetFromIssuerCache`/`getKeySetFromDiscoverURLCache`/`getKeySetFromJWKCache`) and the other data you need (like the `keyID` etc.)
